##[pylyzer] failed /home/dani/advent-of-code-2024/day13/venv/lib/python3.12/site-packages/numpy/_utils/__init__.py 1734628981 3224

.functools = pyimport "<failure>"
.<failure> = pyimport "<failure>"

.warnings = pyimport "<failure>"


.___v_desugar_1 = pyimport "_convertions"
._convertions = pyimport "_convertions"
.asunicode: (s: Obj) -> Str
.asbytes: (s: Obj) -> global::Bytes
.set_module: (module: Obj) -> |Type_1232: Type|(func: Type_1232) -> Type_1232
._rename_parameter: |R: Type, Type_1937: Type|(old_names: global::Iterable(R), new_names: global::Iterable(R), dep_version: Never := Never) -> |Type_1937: Type|(fun: () -> Type_1937) -> (*args: Obj, **kwargs := ?1310) -> Never
